name: mjlab_robocrane
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - cmake
  - ninja
  - git
  - ffmpeg
  - glfw
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - --extra-index-url https://py.mujoco.org
      - --extra-index-url https://pypi.nvidia.com
      - torch==2.7.1
      - torchvision==0.22.1
      - mujoco>=3.5.0
      - mujoco-warp>=3.5.0
      - warp-lang>=1.12.0.dev0
      - gymnasium>=0.29.1
      - prettytable
      - tqdm
      - tyro>=1.0.1
      - torchrunx>=0.3.4
      - trimesh>=4.8.3
      - viser>=1.0.21
      - mediapy>=1.2.6
      - imageio-ffmpeg
      - tensordict>=0.7.0
      - tensorboard>=2.20.0
      - onnx
      - onnxscript>=0.5.4
      - wandb>=0.22.3
      - rsl-rl-lib
      - mjlab
